## Preface I Why this book {.unnumbered}
### It involves a general topic: life.
This book introduces a framework for life management and decision-making. The framework came up to me after years of wondering about the meaning of life, or putting it another way, how to live a meaningful life. In specific, it involves what are the differences between people and how to decide what to do in the future and for now, especially when hesitating on which choice to take, which way to go and what skills to learn. 

### There are a lot of books ...
In the face of these problems, there shows a list of famous literature and popular books on life management and decision making. They may be profound or practical, for example, Principles by Ray Dalio, The Road Less Traveled by M. Scott Peck, The 7 Habits of Highly Effective People by Stephen R. Covey, Rich Dad Poor Dad by Robert Kiyosaki and Sharon Lechter, etc. The list can go on and on if you continue clicking the recommended books on Amazon. 

### This book is above them as ...
Yet there is no such book --- at least to the best of my knowledge ---  that integrates all knowledge in one framework. I don't have the ambition nor the ability to write something more profound than any of these listed books, but I do want to make one thing simple clear and provide a framework that unites these books. When shared with my friends, the framework is praised as reasonable, simple and practicable.  After several months of refining, I wrote this book and presented it for your reference.  


<div style="text-align: right">Ph.D Candidate</div>
<div style="text-align: right">Wenyao Liu</div>
<div style="text-align: right">Oklahoma State Universtiy</div>
<div style="text-align: right">2022-05-27 | Stillwater, OK, U.S.A</div>

