# Preface II My Experience {#sec-experience .unnumbered}

## **Let's begin with my story**

**When I was young**, studying in a village primary school, I concentrated
on --- whether self-motivated or forced by my parents --- studying only two
subjects, Math and Chinese language. Later in middle school, the number of
subjects have increased from two to nine, with the addition of English,
Science, Physics, Chemistry, History, Geometry, and Ideological or Moral.
Some classmates felt difficult but I kept them to be just courses. I
achieved good grades following the same strategy by listening carefully on
classes, understanding the definitions and practicing on some typical
problems. Thanks to this strategy and devotional work, **I was always in
the top 1 or 2 among my peers and had achieved nice grades in Gaokao**, a
nationwide college entrance exam in China, similar to SAT in the U.S., but
hold only one time and is generally only open to Grade 12. I was regarded
as intelligent and admitted to college.

**Things changed after I went to college**, Hunan University, located in
Changsha, China. I moved from the village or county high school to the
province (just like state in the U.S.) capital. It resembles, though I
haven't realized at that time, the ending of an undisturbed,
private-centered and study-only school life. Hunan University is one of the
first-class universities in China and it is famous not only for its
academic reputation but also for its open campus. Although in the U.S.
universities were often wall surrounded, it is rare in China for a high
level university to distribute its buildings in the city with roads, shops
and city residents interspersed. Studying on an open campus with classmates
from different parts of China, changing to the various city living styles,
and dealing with complex college courses, **I came to be wondering why
people are different, the meaning of life, how to succeed, what to do in
the future and what should I learn now.**

The mystification about the future and present drove me to continue
studying for a master's degree when I graduate, to quit a nice job in Hunan
Architecture Design Institute, and to pursue a Ph.D. degree in the U.S. **I
made these decisions not because I was fully considered, but because the
saying of others and the trend of the peers.** These decisions seem
intelligent for most people but not excellent as we expected. The sorrows
behind the glorious "highly educated oversea" is hard to describe but can
be painful when a man got separated from his parents, lover, relatives and
friends for more than three years, not voluntarily but forced by invisible
walls due to the COVID 19 pandemic and international political conflicts.

However, when I look back on these decisions after getting through the
sorrows and pains, **there is always a logic deep in my mind, that is to
learn something and keep learning when wondering which way to go.** This
logic brings the things learned in mind, while not necessarily bringing
wealth or fortune, but at least has a lower chance of making mistakes.

## **Here is the problem...**

**The problem is there are always many things to learn.** All I need to
learn before university is on the courses. After that, I confronted so many
things to learn, either necessary, useful, amazing or interesting. For
example, how to cook and eat healthily, how to dress, where to rent a
cost-effective apartment, how to transport by train or plane, how to buy
and fix cars, how to communicate with others, how to collaborate with
people or manage a task, why economics works in this way, what is behind
the politics, what is behind the data, whether the stock is increasing, how
to make a blog, how to make videos and earn from posts, how Luffy is going
to beat Kaido and win the one-piece, how the Marvel universe absorbed
Chinese elements... So many things to learn!

**But the time and energy of one person are always limited.** I realized
myself easily distracted by the idea to study something "not important"
when doing something "important". Sometimes it gets even more annoying when
the "not important" is more interesting 😂. In fact, for a long
time, I was criticized by true friends saying that I have a lot of ideas
but not digging deep into one specific area. I thank my friends for they
true words and nice advice, but it is still really confusing as the
"unimportant" for the present may change to "important". We may find a lot of
such examples in history or life experiences that the unexpected popping
idea, "unimportant" skills, and "impolite" talks brought out innovations or
chances. So here comes the question, **is there a unifying decision
principle or decision system in mind that can tell us why and what should
I do now?**

## **My final solution:** {#sec-pre-solution}

::: {style="text-align: right"}
Ph.D Candidate <br>
Wenyao Liu <br>
Oklahoma State Universtiy<br>
2022-05-27 \| Stillwater, OK, U.S.A
:::

