# Overview {.unnumbered}

As introduced in [Preface II -@sec-pre-solution], the core of the proposed framework can be summarized within three sentences: 

1.  **The meaning of life should be defined by one himself/herself.**
2.  **The thing that really matters is the view of the future and the ability to get prepared.**
3.  **Learn to view the future and do something to get prepared.**

Let's get a close look at one point after another. 

## The meaning of life
Almost everyone comes up with these questions as they grow up: where are we from? what do I live for? what is the meaning of my life? Then we read books, get talks, or do something that can give us the answer or prove our life is meaningful. The answer may vary from religious belief, political faith, prophetic destiny, determined dreams, or developed interests. I saw some people believing they are chosen to protect the weak, some fighting for power, some earning money for family happiness, some for the environment, some for the education...

There is no subject rule that one's meaning is more meaningful than the other. Everyone, including those who have no idea about the meaning of life, has the same rights and all have the chance to live life to their end. **The thing is that the meaning of life should and can only be defined by oneself, even the one is persuaded or motivated**. **This is the first equality: everyone can control their mind and make their own decisions**. 

## The major difference
**The other equal is the equality in front of time**. The billionaire and the poor, the powerful and the ordinary, the beauty and the ugly all have the same 24 hours for one day and 60 minutes for one hour. However, people born similarly can live a different life when it comes to end. And people born differently may live a similar life when they are getting old. Why? What is making the difference? It's the decisions and the efforts. Specifically, its the view of the future that makes people make decisions, and the preparation for the future are regarded as efforts. 

Lots of examples can be used for illustrating this view. Take the stock market as an example, what makes the difference is your view on the future of one stock and how to buy and sell it, either in the long run or in the short term. As an extreme example for the long run, a little-known John born in a poor family can become a millionaire if he bought 10 dollars of BitCoin in 2010. A well-known billionaire Mike may go broke if he bought BitCoin in December 2021. 

The praised qualities and preferred conditions are always correlated with the view of the future and the ability to get prepared. For example, honesty. People tend to not do business with those lying because we view a higher risk of being cheated and lower certainty about the future. Or, punctuality. Punctual people are praised because their partners get easier to view the future, and they proved their capability in preparation. Or, wisdom. The wisdom in analyzing the past and revealing the principles behind the surface behaviors or phenomena are believed to provide the power on predicting the future. In the cinema, people love the magic stories and valiant heroes because they either view the future or worked very hard to get things prepared for the future they want it to be. Outside the screen, the rich, clever, and powerful people are more attractive in most circumstances because they are believed to have a clearer view of the future and more reliable preparation, though the fact may not be not so. 

## Learn to view and get prepared
You may stop here, take a coffee, and think about point 2 to see if it is simple but reasonable. If you feel the same as me that this view provides a framework for integrating all that you learned and valued, we can move on and see how we can make it practical --- learn to view the future and get prepared. 

Many people of wisdom have contributed to this point and I am also a learner on the way. I suggest that you take point 2 and build your own framework in point 3. But if allowed, I would attempt in providing some references. The following chapters in two parts are the fundamentals of my framework and you don't have to agree with them. 

Last but most important, you are welcome to comment and share the building blocks of your framework on how to view the future and how to get prepared. 

