project:
  type: book
  output-dir: docs
  # output-dir: docs
  # output-file: "my-book"
  
book:
  title: "View the Future and Get Prepared"
  author: "Wenyao Liu"
  # date: "5/25/2022"
  repo-url: https://github.com/wenyaoliu/view-future-get-prepared
  # repo-actions: [edit, issue, source]
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  cover-image: images/book_cover.png
  google-analytics: "G-M8B7M5MHJW"
  sidebar:
    title: "View the Future"
    subtitle: "and Get Prepared"
    logo: images/paperplane2.png
    # style: docked
    style: floating
    alignment: center
    # background: light
  margin-header: |
    ![](images/Paypal_Tip_Me_2.png)
  search: true
  page-navigation: true
  page-footer: 
    center: "Copyright 2022 [Wenyao Liu](https://www.wenyaoliu.com)" 
    # right: 
    #   - icon: github
    #     href: https://github.com/wenyaoliu
    #   - icon: linkedin 
    #     href: https://twitter.com/
    # 
  chapters:
    - index.qmd
    - 01_preface1_why.qmd
    - 02_preface2_experience.qmd
    - 03_overview.qmd
      # - 01_intro.qmd
      # - 02_summary.qmd
    # - part: index.qmd
      # chapters:
        # - 00_why_write.qmd
        # - 01_intro.qmd
        # - 02_summary.qmd
    - part: 10__________Part_1_View-the-future.qmd
      chapters: 
        - 11_models.qmd
        - 12_people.qmd
        - 13_economics.qmd
        - 14_techniques.qmd
    - part: 20__________Part_2_Get-prepared.qmd
      chapters: 
        - 21_self_management.qmd
        - 22_time_management.qmd
        - 23_task_management.qmd
        - 24_resource_management.qmd
        - 25_risk_management.qmd
    - 99_acknowledge.qmd
    - 100_references.qmd
  # appendices:
  #       - index.qmd
  #       - index.qmd
    

bibliography: references.bib

comments:
  hypothesis: true
  
format:
  html:
    theme: solar
      # light: default
      # light: cerulean
      # light: cosmo
      # light: flatly
      # light: journal
      # light: litera
      # light: lumen
      # light: lux
      # light: materia
      # light: minty
      
      # light: pulse
      
      # Colorful theme
      # light: quartz
      # light: sandstone
      # light: simplex
      
      # Sketch font
      # light: sketchy
      
      # light: sandstone
      # light: spacelab
      
      # light: sandstone
      # light: united
      # light: yeti
      # light: zephyr
      
      # Blue background theme
      # light: morph
      
      # Dark Blue
      # dark: superhero
      # dark: vapor
      
      # dark: solar
      # dark: cyborg
      # dark: darkly
      # dark: slate
      
    page-layout: full
  # pdf:
  #   documentclass: scrreprt
  # epub:
  #   cover-image: cover.png

editor: visual

