project:
  type: book
  output-dir: docs
  # output-dir: docs
  # output-file: "my-book"
  
book:
  title: "View the Future and Get Prepared"
  author: "Wenyao Liu"
  date: "5/25/2022"
  repo-url: https://github.com/wenyaoliu/view_future_get_prepared
  # repo-actions: [edit, issue, source]
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  # cover-image: images/gears-535511_640.jpg
  google-analytics: "G-M8B7M5MHJW"
  sidebar:
    title: "View the Future"
    subtitle: "and Get Prepared"
    logo: images/paperplane.png
    # style: docked
    style: floating
    alignment: center
    # background: light
  margin-header: |
    ![](images/Paypal_Tip_Me_2.png)
  search: true
  page-navigation: true
  page-footer: 
    center: "Copyright 2022 [Wenyao Liu](https://www.wenyaoliu.com)" 
    # right: 
    #   - icon: github
    #     href: https://github.com/wenyaoliu
    #   - icon: linkedin 
    #     href: https://twitter.com/
    # 
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_summary.qmd
    - references.qmd
    - part: "Part 1"
      chapters: 
        - 01_intro.qmd
        - 02_summary.qmd

bibliography: references.bib

comments:
  hypothesis: true
  
format:
  html:
    theme: 
      # light: default
      # light: cerulean
      #light: cosmo
      #light: flatly
      light: journal
      #light: flatly
      #light: flatly
      #light: flatly
      #light: flatly
      dark: darkly
      # dark: cyborg
    page-layout: full
  # pdf:
  #   documentclass: scrreprt
  # epub:
  #   cover-image: cover.png

editor: visual

