## Welcome {.unnumbered}

This is the website for "**View the future and Get Prepared**". This book introduces a framework for life management and decision-making. Despite the existence of famous literature and popular books on this topic, the framework in this book is praised as simple, reasonable, and practicable. Hope you can benefit from this framework and live a better life!
<p>&nbsp;</p>
::: {.callout-note appearance="simple"}
This book was created using [Quarto](https://quarto.org) publishing system and published online at [Github Pages](https://github.com/wenyaoliu/view-future-get-prepared).
:::

## Usage

 You can click the **Edit this page** or **Report an issue** on the right panel. A comment system named [Hypothesis](https://hypothes.is/) is enabled on the right side and you are welcome to comment or highlight. 

## License
This website is **free to read**, while **all rights are reserved for the author**. If you'd like to give back, please consider reporting a typo or leaving a pull request at [the GitHub respitory](https://github.com/wenyaoliu/view-future-get-prepared).